# Generated by Django 5.0.6 on 2024-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('date_of_birth', models.CharField(max_length=25, verbose_name='Date of Birth')),
                ('microdistrict', models.TextField(default='', verbose_name='Micro_District')),
                ('residentail_area', models.TextField(default='', verbose_name='Residentail_are')),
                ('street', models.TextField(default='', verbose_name='Street')),
                ('house_number', models.TextField(default='', verbose_name='House_Number')),
                ('apartment_number', models.TextField(default='', verbose_name='ApartmentNumber')),
                ('type_gift', models.CharField(max_length=255, verbose_name='Type of Gift')),
                ('text', models.TextField(verbose_name='Text')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='TypeGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type_ru', models.CharField(default='non', max_length=255, verbose_name='Gift Type (RU)')),
                ('gift_type_kg', models.CharField(default='non', max_length=255, verbose_name='Gift Type (KG)')),
            ],
            options={
                'verbose_name': 'Type of Gift',
                'verbose_name_plural': 'Types of Gift',
            },
        ),
    ]
