# Generated by Django 5.0.6 on 2024-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_kg', models.CharField(max_length=255, verbose_name='Kyrgyz Button')),
                ('button_ru', models.CharField(max_length=255, verbose_name='Russian Button')),
                ('pkname', models.CharField(choices=[('Back', 'Back'), ('Connect', 'Connect'), ('AreaInfo', 'AreaInfo'), ('Gift', 'Gift'), ('ChoiceMenu', 'ChoiceMenu'), ('ChoiceLang', 'ChoiceLang'), ('Menu', 'Menu'), ('Yes', 'Yes'), ('No', 'No'), ('GoToMenu', 'GoTuMenu'), ('NoAgain', 'NoAgain'), ('Skip', 'Skip'), ('ResidentailArea', 'ResidentailArea'), ('Microdistrict', 'Microdistrict')], default='Back', max_length=255, verbose_name='Button Type')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
            },
        ),
    ]
