# Generated by Django 5.0.6 on 2024-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botwords_ru', models.TextField(verbose_name='Russian Text')),
                ('botwords_kg', models.TextField(verbose_name='Kyrgyz Text')),
                ('pkwords', models.CharField(choices=[('Greetings', 'Greetings'), ('ChangeLang', 'ChangeLang'), ('InfoOctoberArea', 'InfoOctoberArea'), ('Mtb', 'Mtb'), ('Med', 'Med'), ('OOU', 'OOU'), ('Connect', 'Connect'), ('Links', 'Links'), ('Contacts', 'Contacts'), ('Choice', 'Choice'), ('GoToMenu', 'GoToMenu'), ('ChoiceGift', 'ChoiceGift'), ('Questionnaire', 'Questionnaire'), ('StartQuestionnaire', 'StartQuestionnaire'), ('ChoiceGiftQuestionnaire', 'ChoiceGiftQuestionnaire'), ('AnswerName', 'AnswerName'), ('AnswerPhoneNumber', 'AnswerPhoneNumber'), ('AnswerDateOfBirth', 'AnswerDateOfBirth'), ('AnswerAdress', 'AnswerAdress'), ('EndQuestionnaire', 'EndQuestionnaire'), ('Gift', 'Gift'), ('Name', 'Name'), ('Phone', 'Phone'), ('BirthDate', 'BirthDate'), ('Address', 'Address'), ('SendQuestionnaire', 'SendQuestionnaire'), ('WarningWord', 'WarningWord'), ('DataSend', 'DataSend'), ('CorrectNumber', 'CorrectNumber'), ('CorrectDate', 'CorrectDate'), ('AdditionalInfoRequest', 'AdditionalInfoRequest'), ('AdditionalText', 'AdditionalText'), ('AnswerDistrict', 'AnswerDistrict'), ('AnswerStreet', 'AnswerStreet'), ('AnswerApartmentNumber', 'AnswerApartmentNumber'), ('AnswerHouseNumber', 'AnswerHouseNumber'), ('District', 'District'), ('Street', 'Street'), ('HouseNumber', 'HouseNumber'), ('ApartmentNumber', 'ApartmentNumber'), ('DefaultStreetWord', 'DefaultStreetWord'), ('IfNotInfo', 'IfNotInfo'), ('DefaultAdditionalInfo', 'DefaultAdditionalInfo'), ('Defaultdistrict', 'Defaultdistrict'), ('DefaultResidentailArea', 'DefaultResidentailArea'), ('DefaultDistrictWord', 'DefaultDistrictWord'), ('DefaultResidentailAreaWord', 'DefaultResidentailAreaWord'), ('ChoiceResidentailArea', 'ChoiceResidentailArea'), ('ChoiceMicrodistrict', 'ChoiceMicroDistrict'), ('AnswerResidentailArea', 'AnswerResidentailArea'), ('AnswerMicrodistrict', 'AnswerMicroDistrict')], default='Greetings', max_length=255, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'Bot Word',
                'verbose_name_plural': 'Bot Words',
            },
        ),
    ]
