# Generated by Django 5.0.6 on 2024-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=50, verbose_name='Russian Name')),
                ('kg_name', models.CharField(max_length=50, verbose_name='Kyrgyz Name')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=50, verbose_name='Russian Name')),
                ('kg_name', models.CharField(max_length=50, verbose_name='Kyrgyz Name')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
