# Generated by Django 5.0.6 on 2024-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_ru', models.TextField(verbose_name='Russian Text')),
                ('string_kg', models.TextField(verbose_name='Kyrgyz Text')),
                ('pkinstitutions', models.CharField(choices=[('Oou', 'Oou'), ('Med', 'Med')], default='Oou', max_length=255, verbose_name='Institution Type')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Mta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_ru', models.TextField(verbose_name='Russian Text')),
                ('string_kg', models.TextField(verbose_name='Kyrgyz Text')),
            ],
            options={
                'verbose_name': 'MTA',
                'verbose_name_plural': 'MTAs',
            },
        ),
    ]
